using System.Text.Json;
using System.Text.Json.Serialization;
using Weavie.AcpDistribution;
using Weavie.Core.Editor;
using Weavie.Core.Git;
using Weavie.Core.Review;
using Weavie.Core.Sessions;
using Weavie.Core.Sources;
using Weavie.Core.Spelling;
using Weavie.Core.Theming;
using Weavie.Core.Tips;
using Weavie.Hosting;
using Weavie.Hosting.Agents;
using Weavie.Hosting.Desktop;
using Weavie.Hosting.Inference.Claude;
using Weavie.Hosting.Web;

namespace Weavie.Hosting.Messaging;

/// <summary>The empty JSON object: an event handler's response and a payload-less event.</summary>
internal sealed record EmptyPayload {
	public static EmptyPayload Value { get; } = new();
}

/// <summary>Source-generated contracts for every payload crossing the web message bus (web defaults: camelCase).</summary>
[JsonSourceGenerationOptions(JsonSerializerDefaults.Web)]
[JsonSerializable(typeof(EmptyPayload))]
[JsonSerializable(typeof(ControlStatus))]
[JsonSerializable(typeof(MessageHealthSnapshot))]
[JsonSerializable(typeof(AgentPlanShown))]
[JsonSerializable(typeof(AgentPlanRemoved))]
[JsonSerializable(typeof(SourceTokenPrompt))]
[JsonSerializable(typeof(SourceLoading))]
[JsonSerializable(typeof(SourceLoadError))]
[JsonSerializable(typeof(SourceDocument))]
[JsonSerializable(typeof(LogsDocument))]
[JsonSerializable(typeof(LogsData))]
[JsonSerializable(typeof(DrainPending))]
[JsonSerializable(typeof(SearchResultWire))]
[JsonSerializable(typeof(SessionAddressData))]
[JsonSerializable(typeof(SessionActivation))]
[JsonSerializable(typeof(CreatedSessionActivation))]
[JsonSerializable(typeof(SessionDeletePreview))]
[JsonSerializable(typeof(TerminalActivation))]
[JsonSerializable(typeof(LspServerWire[]))]
[JsonSerializable(typeof(ClaudeFastModeSettings))]
[JsonSerializable(typeof(HostCore.AgentAsideCommand))]
[JsonSerializable(typeof(HostCore.AgentRewindCommand))]
[JsonSerializable(typeof(NewSessionRequest))]
[JsonSerializable(typeof(HandoffRequest))]
[JsonSerializable(typeof(HandoffReply))]
[JsonSerializable(typeof(HostCore.EditorSessionMessage))]
[JsonSerializable(typeof(AuthenticationTerminalState))]
[JsonSerializable(typeof(AgentPaneWire))]
[JsonSerializable(typeof(AgentPaneBatch))]
[JsonSerializable(typeof(AgentPaneHistoryBatch))]
[JsonSerializable(typeof(AgentQueueMessage))]
[JsonSerializable(typeof(AgentControlsMessage))]
[JsonSerializable(typeof(AgentUsageMessage))]
[JsonSerializable(typeof(OmnibarFocus))]
[JsonSerializable(typeof(ToastMessage))]
[JsonSerializable(typeof(ToastKey))]
[JsonSerializable(typeof(GlobalHostFeatures.InstallResult))]
[JsonSerializable(typeof(AttentionRaised))]
[JsonSerializable(typeof(NotificationActivated))]
[JsonSerializable(typeof(WindowStateChanged))]
[JsonSerializable(typeof(GitStatusSnapshot))]
[JsonSerializable(typeof(PullRequestStatusSnapshot))]
[JsonSerializable(typeof(ApplicationMenuActivation))]
[JsonSerializable(typeof(OpenPathRequest))]
[JsonSerializable(typeof(RefLinkBase))]
[JsonSerializable(typeof(HostCore.SessionCatalogEntry[]))]
[JsonSerializable(typeof(SessionStatusChanged))]
[JsonSerializable(typeof(SourceEditError))]
[JsonSerializable(typeof(SuggestionsChanged))]
[JsonSerializable(typeof(PaneFocus))]
[JsonSerializable(typeof(TestProfileChanged))]
[JsonSerializable(typeof(StartupTip))]
[JsonSerializable(typeof(PullRequestCommentsWire))]
[JsonSerializable(typeof(RemoteAgentsChanged))]
[JsonSerializable(typeof(HostCore.RailSnapshot))]
[JsonSerializable(typeof(HostCore.SearchSnapshot))]
[JsonSerializable(typeof(RecentWorkspacesChanged))]
[JsonSerializable(typeof(RecentFilesChanged))]
[JsonSerializable(typeof(FileProviderChanged))]
[JsonSerializable(typeof(FileIndexWire))]
[JsonSerializable(typeof(AttachmentState))]
[JsonSerializable(typeof(SubmissionState))]
[JsonSerializable(typeof(LspExitWire))]
[JsonSerializable(typeof(LspDataWire))]
[JsonSerializable(typeof(DiffClosed))]
[JsonSerializable(typeof(McpDiffPresenter.DiffWire))]
[JsonSerializable(typeof(DiffSnapshot))]
[JsonSerializable(typeof(ReviseState))]
[JsonSerializable(typeof(ShellTerminalCatalog))]
[JsonSerializable(typeof(TerminalOutput))]
[JsonSerializable(typeof(TerminalReset))]
[JsonSerializable(typeof(TerminalExit))]
[JsonSerializable(typeof(EditorOverlayOpened))]
[JsonSerializable(typeof(EditorFileOpened))]
[JsonSerializable(typeof(EditorTabClosed))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(WireEnvelope))]
[JsonSerializable(typeof(AcpAgentMessage))]
[JsonSerializable(typeof(AcpInstallMessage))]
[JsonSerializable(typeof(HostSession.AgentAuthMessage))]
[JsonSerializable(typeof(HostSession.AgentControlMessage))]
[JsonSerializable(typeof(HostSession.AgentDecisionMessage))]
[JsonSerializable(typeof(HostSession.AgentInputMessage))]
[JsonSerializable(typeof(AgentPaneRecordRequest))]
[JsonSerializable(typeof(GlobalHostFeatures.AgentProviderRequest))]
[JsonSerializable(typeof(HostSession.AgentSideReplyMessage))]
[JsonSerializable(typeof(HostSession.AgentSubmitMessage))]
[JsonSerializable(typeof(ApplicationMenuState))]
[JsonSerializable(typeof(HostSession.AttachmentMessage))]
[JsonSerializable(typeof(HostSession.AttachmentUploadMessage))]
[JsonSerializable(typeof(HostCore.BlameResult))]
[JsonSerializable(typeof(HostCore.BranchPreviewResult))]
[JsonSerializable(typeof(HostSession.ChannelMessage))]
[JsonSerializable(typeof(HostCore.ClipboardImage))]
[JsonSerializable(typeof(HostCore.ClipboardText))]
[JsonSerializable(typeof(HostCore.ClipboardWrite))]
[JsonSerializable(typeof(HostCore.CommandRequest))]
[JsonSerializable(typeof(CommandWireResult))]
[JsonSerializable(typeof(HostCore.CommitHunkRequest))]
[JsonSerializable(typeof(HostCore.CommitHunkResult))]
[JsonSerializable(typeof(HostCore.CommitRefRequest))]
[JsonSerializable(typeof(HostCore.CommitRefResult))]
[JsonSerializable(typeof(HostCore.DiffAgainstMessage))]
[JsonSerializable(typeof(HostCore.DiffRefsResult))]
[JsonSerializable(typeof(HostSession.DiffResolutionMessage))]
[JsonSerializable(typeof(HostSession.DirectoryListingMessage))]
[JsonSerializable(typeof(HostCore.EditorFlushResult))]
[JsonSerializable(typeof(HostCore.FilePathMessage))]
[JsonSerializable(typeof(HostCore.FilePathRequest))]
[JsonSerializable(typeof(FileReadResult))]
[JsonSerializable(typeof(HostSession.FileWriteMessage))]
[JsonSerializable(typeof(FileWriteResult))]
[JsonSerializable(typeof(HostCore.HistoryRequest))]
[JsonSerializable(typeof(HostCore.HistoryResult))]
[JsonSerializable(typeof(HostCore.HostBranchPreviewRequest))]
[JsonSerializable(typeof(HostCore.HostHello))]
[JsonSerializable(typeof(IReadOnlyList<AcpRegistryAgent>))]
[JsonSerializable(typeof(IReadOnlyList<ThemeChoice>))]
[JsonSerializable(typeof(IReadOnlyList<ThemePreview>))]
[JsonSerializable(typeof(HostSession.ImagePasteMessage))]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(HostCore.LayoutResizeMessage))]
[JsonSerializable(typeof(HostSession.ListDirectoryMessage))]
[JsonSerializable(typeof(HostSession.LspDataMessage))]
[JsonSerializable(typeof(HostSession.LspResetMessage))]
[JsonSerializable(typeof(HostSession.LspStartMessage))]
[JsonSerializable(typeof(HostSession.LspStartResult))]
[JsonSerializable(typeof(Misspelling[]))]
[JsonSerializable(typeof(HostCore.NotificationPermissionMessage))]
[JsonSerializable(typeof(HostCore.NotificationShowMessage))]
[JsonSerializable(typeof(HostCore.NotificationShownMessage))]
[JsonSerializable(typeof(HostSession.OpenPlanMessage))]
[JsonSerializable(typeof(HostCore.OpenTargetMessage))]
[JsonSerializable(typeof(HostCore.OpenUrlMessage))]
[JsonSerializable(typeof(HostCore.PullRequestCommentRequest))]
[JsonSerializable(typeof(HostCore.PullRequestEditRequest))]
[JsonSerializable(typeof(HostCore.PullRequestQuery))]
[JsonSerializable(typeof(HostCore.PullRequestReference))]
[JsonSerializable(typeof(HostCore.PullRequestReplyRequest))]
[JsonSerializable(typeof(PullRequestSources))]
[JsonSerializable(typeof(HostCore.PullRequestSourcesRequest))]
[JsonSerializable(typeof(HostCore.PullRequestWire))]
[JsonSerializable(typeof(HostCore.PullRequestWire[]))]
[JsonSerializable(typeof(HostCore.RailLocation))]
[JsonSerializable(typeof(HostCore.RailPromotionSet))]
[JsonSerializable(typeof(HostCore.RailSelectionMessage))]
[JsonSerializable(typeof(HostCore.RemoteAgentMessage))]
[JsonSerializable(typeof(HostCore.RemoteAgentName))]
[JsonSerializable(typeof(HostSession.ResetDirectoryWatchesMessage))]
[JsonSerializable(typeof(HostSession.RevealFileMessage))]
[JsonSerializable(typeof(HostCore.ReviewHistoryLocation))]
[JsonSerializable(typeof(ReviseConfirmReply))]
[JsonSerializable(typeof(ReviseConfirmRequest))]
[JsonSerializable(typeof(HostCore.ReviseStartMessage))]
[JsonSerializable(typeof(HostCore.SaveSourceTokenMessage))]
[JsonSerializable(typeof(HostCore.ScratchSaveResult))]
[JsonSerializable(typeof(HostCore.SearchOptionsMessage))]
[JsonSerializable(typeof(HostCore.SearchTerm))]
[JsonSerializable(typeof(HostCore.SessionSyncResult))]
[JsonSerializable(typeof(GlobalHostFeatures.SettingRead))]
[JsonSerializable(typeof(GlobalHostFeatures.SettingWrite))]
[JsonSerializable(typeof(SourceDoc))]
[JsonSerializable(typeof(HostCore.SourceEditMessage))]
[JsonSerializable(typeof(HostCore.SourceTokenResult))]
[JsonSerializable(typeof(HostCore.SpellAddRequest))]
[JsonSerializable(typeof(HostCore.SpellCheckRequest))]
[JsonSerializable(typeof(HostCore.SpellSuggestRequest))]
[JsonSerializable(typeof(HostCore.SuggestionDismissal))]
[JsonSerializable(typeof(TerminalMessageWiring.TerminalCwdMessage))]
[JsonSerializable(typeof(TerminalMessageWiring.TerminalInputMessage))]
[JsonSerializable(typeof(TerminalMessageWiring.TerminalSizeMessage))]
[JsonSerializable(typeof(GlobalHostFeatures.ThemeExtensionRequest))]
[JsonSerializable(typeof(GlobalHostFeatures.ThemeIdRequest))]
[JsonSerializable(typeof(GlobalHostFeatures.ThemeSearchRequest))]
[JsonSerializable(typeof(HostCore.ToolLayoutMessage))]
[JsonSerializable(typeof(HostSession.UnwatchDirectoryMessage))]
[JsonSerializable(typeof(Weavie.Core.FileSystem.FileStat))]
[JsonSerializable(typeof(GlobalHostFeatures.WebLogMessage))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(string[]))]
internal sealed partial class WireJson : JsonSerializerContext;
