// "Weavie Dark" — the built-in default theme. Authored to read crisp, not washed out: a deep, slightly
// cool charcoal base (#0f1217) under bright near-white text (#e8eaf0), high foreground/background
// contrast, and a deliberately vivid, hue-separated syntax palette anchored on the Weavie teal accent
// (#2dd4bf). Distinct from VS Code's low-saturation Dark+ on purpose. It's a normal VS Code color theme
// (spec §5): the same `colors` map drives the editor, the terminal, and Weavie's chrome, so overrides
// (spec §6) and installed Open VSX themes address the exact same keys.

import type { VsCodeColorTheme } from "../vscode-theme";

/** Stable id Monaco/`setTheme` and `theme.active` reference this built-in by. */
export const WEAVIE_DARK_ID = "weavie-dark";

export const WEAVIE_DARK: VsCodeColorTheme = {
  name: "Weavie Dark",
  type: "dark",
  semanticHighlighting: true,
  colors: {
    // ── Editor ────────────────────────────────────────────────────────────────────────────────────
    "editor.background": "#0f1217",
    "editor.foreground": "#e8eaf0",
    "editorLineNumber.foreground": "#3a4250",
    "editorLineNumber.activeForeground": "#8b95a7",
    "editorCursor.foreground": "#2dd4bf",
    "editor.selectionBackground": "#2dd4bf38",
    "editor.selectionHighlightBackground": "#2dd4bf22",
    "editor.inactiveSelectionBackground": "#2dd4bf1f",
    "editor.wordHighlightBackground": "#6aa8ff22",
    "editor.wordHighlightStrongBackground": "#6aa8ff33",
    "editor.findMatchBackground": "#ff9d5c66",
    "editor.findMatchHighlightBackground": "#ff9d5c33",
    "editor.lineHighlightBackground": "#161a2155",
    "editor.lineHighlightBorder": "#00000000",
    "editorWhitespace.foreground": "#262d39",
    "editorIndentGuide.background1": "#1c2330",
    "editorIndentGuide.activeBackground1": "#2dd4bf55",
    "editorBracketMatch.background": "#2dd4bf22",
    "editorBracketMatch.border": "#2dd4bf77",
    "editorBracketHighlight.foreground1": "#6aa8ff",
    "editorBracketHighlight.foreground2": "#ff9d5c",
    "editorBracketHighlight.foreground3": "#ff5d9e",
    "editorRuler.foreground": "#1c2330",
    "editorGutter.addedBackground": "#2ea043",
    "editorGutter.modifiedBackground": "#2dd4bf",
    "editorGutter.deletedBackground": "#d25a5a",
    "editorError.foreground": "#ff6e7a",
    "editorWarning.foreground": "#ffc86b",
    "editorInfo.foreground": "#6aa8ff",

    // ── Widgets (hover, suggest, find, peek) ────────────────────────────────────────────────────────
    "editorWidget.background": "#12161d",
    "editorWidget.border": "#232a35",
    "editorHoverWidget.background": "#12161d",
    "editorHoverWidget.border": "#232a35",
    "editorSuggestWidget.background": "#12161d",
    "editorSuggestWidget.border": "#232a35",
    "editorSuggestWidget.selectedBackground": "#1d2530",
    "editorSuggestWidget.highlightForeground": "#2dd4bf",
    "peekViewEditor.background": "#0d1015",
    "peekViewResult.background": "#0b0d11",

    // ── Global / shared ─────────────────────────────────────────────────────────────────────────────
    focusBorder: "#2dd4bf",
    foreground: "#cdd3df",
    descriptionForeground: "#8b95a7",
    errorForeground: "#ff6e7a",
    "icon.foreground": "#8b95a7",
    "selection.background": "#2dd4bf55",
    "widget.border": "#232a35",
    "sash.hoverBorder": "#2dd4bf",

    // ── Chrome surfaces (sidebar / panel / status / title / tabs) ────────────────────────────────────
    "editorGroup.border": "#232a35",
    "editorGroupHeader.tabsBackground": "#0b0d11",
    "panel.background": "#0b0d11",
    "panel.border": "#232a35",
    "panelTitle.activeForeground": "#e8eaf0",
    "sideBar.background": "#0b0d11",
    "sideBar.foreground": "#cdd3df",
    "sideBar.border": "#232a35",
    "sideBarSectionHeader.background": "#0b0d11",
    "activityBar.background": "#0b0d11",
    "activityBar.foreground": "#e8eaf0",
    "statusBar.background": "#0b0d11",
    "statusBar.foreground": "#8b95a7",
    "statusBar.border": "#232a35",
    "statusBar.noFolderBackground": "#0b0d11",
    "statusBarItem.remoteBackground": "#2dd4bf",
    "statusBarItem.remoteForeground": "#04201c",
    "titleBar.activeBackground": "#0b0d11",
    "titleBar.activeForeground": "#cdd3df",
    "titleBar.inactiveBackground": "#0b0d11",
    "titleBar.inactiveForeground": "#647084",
    "titleBar.border": "#232a35",
    "tab.activeBackground": "#0f1217",
    "tab.activeForeground": "#e8eaf0",
    "tab.inactiveBackground": "#0b0d11",
    "tab.inactiveForeground": "#647084",
    "tab.border": "#232a35",
    "tab.activeBorderTop": "#2dd4bf",
    "tab.hoverBackground": "#12161d",

    // ── Controls (buttons, inputs, lists, scrollbar) ────────────────────────────────────────────────
    "button.background": "#2dd4bf",
    "button.foreground": "#04201c",
    "button.hoverBackground": "#3ee0cc",
    "button.secondaryBackground": "#1d2530",
    "button.secondaryForeground": "#e8eaf0",
    "input.background": "#0f1217",
    "input.foreground": "#e8eaf0",
    "input.border": "#232a35",
    "input.placeholderForeground": "#647084",
    "inputOption.activeBorder": "#2dd4bf",
    "inputOption.activeBackground": "#2dd4bf33",
    "dropdown.background": "#12161d",
    "dropdown.border": "#232a35",
    "list.activeSelectionBackground": "#1d2530",
    "list.activeSelectionForeground": "#e8eaf0",
    "list.inactiveSelectionBackground": "#161a21",
    "list.hoverBackground": "#161a21",
    "list.highlightForeground": "#2dd4bf",
    "list.focusBackground": "#1d2530",
    "scrollbar.shadow": "#00000066",
    "scrollbarSlider.background": "#2a313c80",
    "scrollbarSlider.hoverBackground": "#3a4250aa",
    "scrollbarSlider.activeBackground": "#4a5666cc",
    "badge.background": "#2dd4bf",
    "badge.foreground": "#04201c",
    "progressBar.background": "#2dd4bf",

    // ── Terminal (xterm consumes these) ─────────────────────────────────────────────────────────────
    "terminal.background": "#0b0d11",
    "terminal.foreground": "#cdd3df",
    "terminalCursor.foreground": "#2dd4bf",
    "terminal.selectionBackground": "#2dd4bf33",
    "terminal.ansiBlack": "#0b0d11",
    "terminal.ansiRed": "#e2696f",
    "terminal.ansiGreen": "#8fbf6a",
    "terminal.ansiYellow": "#d9b56a",
    "terminal.ansiBlue": "#6f9bd6",
    "terminal.ansiMagenta": "#cf6f99",
    "terminal.ansiCyan": "#46bdb0",
    "terminal.ansiWhite": "#cdd3df",
    "terminal.ansiBrightBlack": "#647084",
    "terminal.ansiBrightRed": "#ef8189",
    "terminal.ansiBrightGreen": "#a6cf80",
    "terminal.ansiBrightYellow": "#e6c884",
    "terminal.ansiBrightBlue": "#8fb4e6",
    "terminal.ansiBrightMagenta": "#df8aaf",
    "terminal.ansiBrightCyan": "#6fd0c4",
    "terminal.ansiBrightWhite": "#e8eaf0",
  },
  tokenColors: [
    {
      name: "Comment",
      scope: ["comment", "punctuation.definition.comment", "string.comment"],
      settings: { foreground: "#647084", fontStyle: "italic" },
    },
    {
      name: "String",
      scope: ["string", "string.quoted", "punctuation.definition.string"],
      settings: { foreground: "#a7e05a" },
    },
    {
      name: "String escape / template expression",
      scope: [
        "constant.character.escape",
        "constant.other.placeholder",
        "punctuation.definition.template-expression",
      ],
      settings: { foreground: "#56d9c6" },
    },
    { name: "Regexp", scope: ["string.regexp"], settings: { foreground: "#8be0c0" } },
    {
      name: "Number / constant",
      scope: ["constant.numeric", "constant.character", "keyword.other.unit"],
      settings: { foreground: "#ff9d5c" },
    },
    {
      name: "Language constant (true/false/null)",
      scope: [
        "constant.language",
        "constant.language.boolean",
        "constant.language.null",
        "constant.language.undefined",
      ],
      settings: { foreground: "#ff9d5c" },
    },
    {
      name: "Keyword / control",
      scope: [
        "keyword",
        "keyword.control",
        "keyword.operator.new",
        "keyword.operator.expression",
        "keyword.operator.logical",
      ],
      settings: { foreground: "#ff5d9e" },
    },
    {
      name: "Storage / type keyword / modifier",
      scope: ["storage", "storage.type", "storage.modifier", "keyword.declaration"],
      settings: { foreground: "#ff5d9e" },
    },
    {
      name: "Operator / accessor",
      scope: ["keyword.operator", "punctuation.accessor", "punctuation.separator"],
      settings: { foreground: "#56d9c6" },
    },
    {
      name: "Type / class / namespace",
      scope: [
        "entity.name.type",
        "entity.name.class",
        "entity.name.namespace",
        "support.type",
        "support.class",
        "entity.other.inherited-class",
      ],
      settings: { foreground: "#4dd6c4" },
    },
    {
      name: "Function / method",
      scope: [
        "entity.name.function",
        "support.function",
        "meta.function-call entity.name.function",
        "entity.name.function.member",
      ],
      settings: { foreground: "#6aa8ff" },
    },
    {
      name: "Variable",
      scope: ["variable", "meta.variable", "variable.other.readwrite"],
      settings: { foreground: "#e8eaf0" },
    },
    {
      name: "Parameter",
      scope: ["variable.parameter", "meta.parameter"],
      settings: { foreground: "#d3b6ff" },
    },
    {
      name: "Property",
      scope: [
        "variable.other.property",
        "variable.other.object.property",
        "support.variable.property",
        "meta.object-literal.key",
      ],
      settings: { foreground: "#8fd0ff" },
    },
    {
      name: "Constant / enum member",
      scope: ["variable.other.constant", "variable.other.enummember"],
      settings: { foreground: "#ff9d5c" },
    },
    {
      name: "Language variable (this / self / super)",
      scope: ["variable.language", "variable.language.this"],
      settings: { foreground: "#ff5d9e", fontStyle: "italic" },
    },
    {
      name: "Tag",
      scope: ["entity.name.tag", "punctuation.definition.tag"],
      settings: { foreground: "#ff6e8a" },
    },
    {
      name: "Tag attribute",
      scope: ["entity.other.attribute-name"],
      settings: { foreground: "#ffc86b", fontStyle: "italic" },
    },
    {
      name: "Decorator / annotation",
      scope: [
        "meta.decorator",
        "punctuation.decorator",
        "storage.type.annotation",
        "entity.name.function.decorator",
      ],
      settings: { foreground: "#ffc86b" },
    },
    {
      name: "JSON key",
      scope: ["support.type.property-name.json", "meta.structure.dictionary.key.json"],
      settings: { foreground: "#8fd0ff" },
    },
    {
      name: "Punctuation / braces",
      scope: ["punctuation", "meta.brace"],
      settings: { foreground: "#9aa3b2" },
    },
    {
      name: "Markup heading",
      scope: ["markup.heading", "entity.name.section"],
      settings: { foreground: "#6aa8ff", fontStyle: "bold" },
    },
    {
      name: "Markup bold",
      scope: ["markup.bold"],
      settings: { foreground: "#ff9d5c", fontStyle: "bold" },
    },
    {
      name: "Markup italic",
      scope: ["markup.italic"],
      settings: { foreground: "#ff9d5c", fontStyle: "italic" },
    },
    {
      name: "Markup link",
      scope: ["markup.underline.link", "string.other.link"],
      settings: { foreground: "#2dd4bf" },
    },
    {
      name: "Markup inline / fenced code",
      scope: ["markup.inline.raw", "markup.fenced_code"],
      settings: { foreground: "#a7e05a" },
    },
    { name: "Markup inserted", scope: ["markup.inserted"], settings: { foreground: "#a7e05a" } },
    { name: "Markup deleted", scope: ["markup.deleted"], settings: { foreground: "#ff6e7a" } },
    { name: "Invalid", scope: ["invalid", "invalid.illegal"], settings: { foreground: "#ff6e7a" } },
  ],
  semanticTokenColors: {
    class: "#4dd6c4",
    interface: "#4dd6c4",
    enum: "#4dd6c4",
    struct: "#4dd6c4",
    type: "#4dd6c4",
    namespace: "#4dd6c4",
    typeParameter: "#d3b6ff",
    enumMember: "#ff9d5c",
    function: "#6aa8ff",
    method: "#6aa8ff",
    macro: "#ffc86b",
    variable: "#e8eaf0",
    "variable.readonly": "#ff9d5c",
    parameter: "#d3b6ff",
    property: "#8fd0ff",
    "property.readonly": "#8fd0ff",
  },
};
