// "Weavie Light" — Soft Paper companion to Weavie Dark on a dimmed canvas (#e3e2da). Identifier roles are
// split by hue and luminance so they never blur: variables deep royal blue (~6.3:1, the names scanned most),
// properties a lighter steel-blue cousin, functions crimson, types cyan-teal, keywords emerald pitched
// lighter than the blues so the two read as distinct hues. On a light canvas separation comes from spreading
// luminance/hue, not brightness. The same `colors` map drives editor, terminal, and chrome (spec §5).

import type { VsCodeColorTheme } from "../vscode-theme";

/** Stable id Monaco/`setTheme` and the `theme.light`/`theme.dark` settings reference this built-in by. */
export const WEAVIE_LIGHT_ID = "weavie-light";

export const WEAVIE_LIGHT: VsCodeColorTheme = {
  name: "Weavie Light",
  type: "light",
  semanticHighlighting: true,
  colors: {
    // ── Editor ────────────────────────────────────────────────────────────────────────────────────
    "editor.background": "#e3e2da",
    "editor.foreground": "#16202a",
    "editorLineNumber.foreground": "#b6b6ab",
    "editorLineNumber.activeForeground": "#4b5563",
    "editorCursor.foreground": "#1f9d78",
    "editor.selectionBackground": "#1f9d7833",
    "editor.selectionHighlightBackground": "#1f9d781f",
    "editor.inactiveSelectionBackground": "#1f9d7817",
    "editor.wordHighlightBackground": "#1f9d7820",
    "editor.wordHighlightStrongBackground": "#1f9d7830",
    "editor.findMatchBackground": "#1f9d7855",
    "editor.findMatchHighlightBackground": "#1f9d7826",
    "editor.lineHighlightBackground": "#16202a0a",
    "editor.lineHighlightBorder": "#00000000",
    "editorWhitespace.foreground": "#d2d1c9",
    "editorIndentGuide.background1": "#dcdbd3",
    "editorIndentGuide.activeBackground1": "#1f9d7855",
    "editorBracketMatch.background": "#1f9d781f",
    "editorBracketMatch.border": "#1f9d7777",
    "editorBracketHighlight.foreground1": "#1f9d78",
    "editorBracketHighlight.foreground2": "#0a7286",
    "editorBracketHighlight.foreground3": "#6b7682",
    "editorRuler.foreground": "#dcdbd3",
    "editorGutter.addedBackground": "#3f9d5a",
    "editorGutter.modifiedBackground": "#1f9d78",
    "editorGutter.deletedBackground": "#c4666a",
    "editorError.foreground": "#c8413b",
    "editorWarning.foreground": "#b5701a",
    "editorInfo.foreground": "#1f9d78",

    // ── Inlay hints (parameter-name / type chips) ───────────────────────────────────────────────────
    // Quiet and chip-less so they annotate without competing with the code they sit between.
    "editorInlayHint.foreground": "#9aa4b0",
    "editorInlayHint.background": "#00000000",
    "editorInlayHint.typeForeground": "#9aa4b0",
    "editorInlayHint.parameterForeground": "#9aa4b0",

    // ── Widgets (hover, suggest, find, peek) ────────────────────────────────────────────────────────
    "editorWidget.background": "#dbdad2",
    "editorWidget.border": "#d2d1c9",
    "editorHoverWidget.background": "#dfded7",
    "editorHoverWidget.border": "#d2d1c9",
    "editorSuggestWidget.background": "#e7e6e0",
    "editorSuggestWidget.border": "#d2d1c9",
    "editorSuggestWidget.selectedBackground": "#e0dfd8",
    "editorSuggestWidget.highlightForeground": "#1f9d78",
    "peekViewEditor.background": "#e6e5df",
    "peekViewResult.background": "#dbdad2",

    // ── Global / shared ─────────────────────────────────────────────────────────────────────────────
    focusBorder: "#1f9d78",
    foreground: "#232e38",
    descriptionForeground: "#6f7884",
    errorForeground: "#c8413b",
    "icon.foreground": "#6b7682",
    "selection.background": "#1f9d7833",
    "widget.border": "#d2d1c9",
    "sash.hoverBorder": "#1f9d78",

    // ── Chrome surfaces (sidebar / panel / status / title / tabs) ────────────────────────────────────
    // One step darker than the editor, so the canvas reads as the focal well it frames.
    "editorGroup.border": "#d4d3ca",
    "editorGroupHeader.tabsBackground": "#dbdad2",
    "panel.background": "#dbdad2",
    "panel.border": "#d4d3ca",
    "panelTitle.activeForeground": "#16202a",
    "sideBar.background": "#dbdad2",
    "sideBar.foreground": "#34404b",
    "sideBar.border": "#d4d3ca",
    "sideBarSectionHeader.background": "#dbdad2",
    "activityBar.background": "#dbdad2",
    "activityBar.foreground": "#16202a",
    "statusBar.background": "#dbdad2",
    "statusBar.foreground": "#6f7884",
    "statusBar.border": "#d4d3ca",
    "statusBar.noFolderBackground": "#dbdad2",
    "statusBarItem.remoteBackground": "#1f9d78",
    "statusBarItem.remoteForeground": "#ffffff",
    "titleBar.activeBackground": "#dbdad2",
    "titleBar.activeForeground": "#2b3640",
    "titleBar.inactiveBackground": "#dbdad2",
    "titleBar.inactiveForeground": "#9aa4b0",
    "titleBar.border": "#d4d3ca",
    "tab.activeBackground": "#e3e2da",
    "tab.activeForeground": "#11181f",
    "tab.inactiveBackground": "#dbdad2",
    "tab.inactiveForeground": "#79828f",
    "tab.border": "#d4d3ca",
    "tab.activeBorderTop": "#1f9d78",
    "tab.hoverBackground": "#e0dfd8",

    // ── Controls (buttons, inputs, lists, scrollbar) ────────────────────────────────────────────────
    "button.background": "#1f9d78",
    "button.foreground": "#ffffff",
    "button.hoverBackground": "#1c8e6c",
    "button.secondaryBackground": "#dedcd4",
    "button.secondaryForeground": "#2b3640",
    "input.background": "#e9e8e1",
    "input.foreground": "#16202a",
    "input.border": "#cbcabf",
    "input.placeholderForeground": "#9aa4b0",
    "inputOption.activeBorder": "#1f9d78",
    "inputOption.activeBackground": "#1f9d7826",
    "dropdown.background": "#e9e8e1",
    "dropdown.border": "#cbcabf",
    "list.activeSelectionBackground": "#dce6df",
    "list.activeSelectionForeground": "#11181f",
    "list.inactiveSelectionBackground": "#e0dfd8",
    "list.hoverBackground": "#e0dfd8",
    "list.highlightForeground": "#1f9d78",
    "list.focusBackground": "#dce6df",
    "scrollbar.shadow": "#00000018",
    "scrollbarSlider.background": "#16202a2e",
    "scrollbarSlider.hoverBackground": "#16202a44",
    "scrollbarSlider.activeBackground": "#16202a59",
    "badge.background": "#1f9d78",
    "badge.foreground": "#ffffff",
    "progressBar.background": "#1f9d78",

    // ── Terminal (xterm consumes these) ─────────────────────────────────────────────────────────────
    "terminal.background": "#e6e5df",
    "terminal.foreground": "#16202a",
    "terminalCursor.foreground": "#1f9d78",
    "terminal.selectionBackground": "#1f9d7833",
    "terminal.ansiBlack": "#2b3640",
    "terminal.ansiRed": "#c8413b",
    "terminal.ansiGreen": "#2e8b3d",
    "terminal.ansiYellow": "#b06a00",
    "terminal.ansiBlue": "#2f6fb0",
    "terminal.ansiMagenta": "#9356c4",
    "terminal.ansiCyan": "#157f78",
    "terminal.ansiWhite": "#6b7682",
    "terminal.ansiBrightBlack": "#9aa4b0",
    "terminal.ansiBrightRed": "#d85650",
    "terminal.ansiBrightGreen": "#3fa050",
    "terminal.ansiBrightYellow": "#c07f13",
    "terminal.ansiBrightBlue": "#3f80c0",
    "terminal.ansiBrightMagenta": "#a468d0",
    "terminal.ansiBrightCyan": "#1f9d8f",
    "terminal.ansiBrightWhite": "#11181f",
  },
  tokenColors: [
    {
      name: "Comment",
      scope: ["comment", "punctuation.definition.comment", "string.comment"],
      settings: { foreground: "#7d8290" },
    },
    {
      name: "String",
      scope: ["string", "string.quoted", "punctuation.definition.string"],
      settings: { foreground: "#2a7d34" },
    },
    {
      name: "String escape / template expression",
      scope: [
        "constant.character.escape",
        "constant.other.placeholder",
        "punctuation.definition.template-expression",
      ],
      settings: { foreground: "#237f38" },
    },
    { name: "Regexp", scope: ["string.regexp"], settings: { foreground: "#237f38" } },
    {
      name: "Number",
      scope: ["constant.numeric", "constant.character", "keyword.other.unit"],
      settings: { foreground: "#0d7059" },
    },
    {
      name: "Language constant (true/false/null)",
      scope: [
        "constant.language",
        "constant.language.boolean",
        "constant.language.null",
        "constant.language.undefined",
      ],
      settings: { foreground: "#0d7059" },
    },
    {
      name: "Keyword / control",
      scope: [
        "keyword",
        "keyword.control",
        "keyword.operator.new",
        "keyword.operator.expression",
        "keyword.operator.logical",
      ],
      settings: { foreground: "#0d7344" },
    },
    {
      name: "Storage / type keyword / modifier",
      scope: ["storage", "storage.type", "storage.modifier", "keyword.declaration"],
      settings: { foreground: "#0d7344" },
    },
    {
      name: "Operator / accessor",
      scope: ["keyword.operator", "punctuation.accessor", "punctuation.separator"],
      settings: { foreground: "#6b7682" },
    },
    {
      name: "Type / class / namespace",
      scope: [
        "entity.name.type",
        "entity.name.class",
        "entity.name.namespace",
        "support.type",
        "support.class",
        "entity.other.inherited-class",
      ],
      settings: { foreground: "#0a7286" },
    },
    {
      name: "Function / method",
      scope: [
        "entity.name.function",
        "support.function",
        "meta.function-call entity.name.function",
        "entity.name.function.member",
      ],
      settings: { foreground: "#bb3326" },
    },
    {
      name: "Variable",
      scope: [
        "variable",
        "meta.variable",
        "variable.other.readwrite",
        "variable.parameter",
        "meta.parameter",
      ],
      settings: { foreground: "#2849a5" },
    },
    {
      name: "Property",
      scope: [
        "variable.other.property",
        "variable.other.object.property",
        "support.variable.property",
        "meta.object-literal.key",
      ],
      settings: { foreground: "#3a63ac" },
    },
    {
      name: "Constant / enum member",
      scope: ["variable.other.constant", "variable.other.enummember"],
      settings: { foreground: "#0d7059" },
    },
    {
      name: "Language variable (this / self / super)",
      scope: ["variable.language", "variable.language.this"],
      settings: { foreground: "#0d7344" },
    },
    {
      name: "Tag",
      scope: ["entity.name.tag", "punctuation.definition.tag"],
      settings: { foreground: "#0d7344" },
    },
    {
      name: "Tag attribute",
      scope: ["entity.other.attribute-name"],
      settings: { foreground: "#3a63ac" },
    },
    {
      name: "Decorator / annotation",
      scope: [
        "meta.decorator",
        "punctuation.decorator",
        "storage.type.annotation",
        "entity.name.function.decorator",
      ],
      settings: { foreground: "#0a7286" },
    },
    {
      name: "JSON key",
      scope: ["support.type.property-name.json", "meta.structure.dictionary.key.json"],
      settings: { foreground: "#3a63ac" },
    },
    {
      name: "Punctuation / braces",
      scope: ["punctuation", "meta.brace"],
      settings: { foreground: "#818b95" },
    },
    {
      name: "Markup heading",
      scope: ["markup.heading", "entity.name.section"],
      settings: { foreground: "#0a7286", fontStyle: "bold" },
    },
    {
      name: "Markup bold",
      scope: ["markup.bold"],
      settings: { foreground: "#11181f", fontStyle: "bold" },
    },
    {
      name: "Markup italic",
      scope: ["markup.italic"],
      settings: { foreground: "#2b3640", fontStyle: "italic" },
    },
    {
      name: "Markup link",
      scope: ["markup.underline.link", "string.other.link"],
      settings: { foreground: "#1f9d78" },
    },
    {
      name: "Markup inline / fenced code",
      scope: ["markup.inline.raw", "markup.fenced_code"],
      settings: { foreground: "#2a7d34" },
    },
    { name: "Markup inserted", scope: ["markup.inserted"], settings: { foreground: "#2a7d34" } },
    { name: "Markup deleted", scope: ["markup.deleted"], settings: { foreground: "#c8413b" } },
    { name: "Invalid", scope: ["invalid", "invalid.illegal"], settings: { foreground: "#c8413b" } },
  ],
  semanticTokenColors: {
    // Types cyan-teal, distinct from green keywords and blue identifiers; namespaces dimmer (qualifiers).
    class: "#0a7286",
    interface: "#0a7286",
    enum: "#0a7286",
    struct: "#0a7286",
    type: "#0a7286",
    typeParameter: "#3a9aac",
    namespace: "#3a8590",
    // Literal values (numbers, constants, enum members) share the deep sea-green of numbers.
    enumMember: "#0d7059",
    number: "#0d7059",
    "variable.readonly": "#0d7059",
    // Functions are crimson — the lone warm accent — so calls and definitions stand out from the data.
    function: "#bb3326",
    method: "#bb3326",
    macro: "#0d7344",
    keyword: "#0d7344",
    string: "#2a7d34",
    operator: "#6b7682",
    comment: "#7d8290",
    // Variables (incl. parameters) deep blue at ~6.9:1 — scanned most; properties a quieter steel-blue.
    variable: "#2849a5",
    parameter: "#2849a5",
    property: "#3a63ac",
    "property.readonly": "#3a63ac",
  },
};
