// "Weavie Dark" — the built-in default theme. A minimal, premium dark scheme: near-black base (#0a0c10)
// under bright cool-grey text, with code rendered mostly in tonal greys and just two accents — a refined
// teal for keywords + the UI, and a soft green for strings. Few colors, high contrast (Linear/Vercel
// "slick" feel) rather than a rainbow; warm red/yellow appear only where they carry meaning (errors,
// diffs, warnings). It's a normal VS Code color theme (spec §5): the same `colors` map drives the editor,
// the terminal, and Weavie's chrome, so overrides (spec §6) and installed Open VSX themes address the
// exact same keys.

import type { VsCodeColorTheme } from "../vscode-theme";

/** Stable id Monaco/`setTheme` and `theme.active` reference this built-in by. */
export const WEAVIE_DARK_ID = "weavie-dark";

export const WEAVIE_DARK: VsCodeColorTheme = {
  name: "Weavie Dark",
  type: "dark",
  semanticHighlighting: true,
  colors: {
    // ── Editor ────────────────────────────────────────────────────────────────────────────────────
    "editor.background": "#0a0c10",
    "editor.foreground": "#d4d9e1",
    "editorLineNumber.foreground": "#3a4250",
    "editorLineNumber.activeForeground": "#8893a2",
    "editorCursor.foreground": "#5cc0b5",
    "editor.selectionBackground": "#2e4a47aa",
    "editor.selectionHighlightBackground": "#2e4a4755",
    "editor.inactiveSelectionBackground": "#2e4a4733",
    "editor.wordHighlightBackground": "#4fb0a622",
    "editor.wordHighlightStrongBackground": "#4fb0a633",
    "editor.findMatchBackground": "#4fb0a655",
    "editor.findMatchHighlightBackground": "#4fb0a62e",
    "editor.lineHighlightBackground": "#12151c66",
    "editor.lineHighlightBorder": "#00000000",
    "editorWhitespace.foreground": "#232a35",
    "editorIndentGuide.background1": "#181e27",
    "editorIndentGuide.activeBackground1": "#4fb0a644",
    "editorBracketMatch.background": "#4fb0a61f",
    "editorBracketMatch.border": "#4fb0a677",
    "editorBracketHighlight.foreground1": "#4fb0a6",
    "editorBracketHighlight.foreground2": "#b9cda8",
    "editorBracketHighlight.foreground3": "#aab3c0",
    "editorRuler.foreground": "#181e27",
    "editorGutter.addedBackground": "#5a9a6a",
    "editorGutter.modifiedBackground": "#4fb0a6",
    "editorGutter.deletedBackground": "#c47a7a",
    "editorError.foreground": "#d57a7a",
    "editorWarning.foreground": "#c9a36a",
    "editorInfo.foreground": "#4fb0a6",

    // ── Widgets (hover, suggest, find, peek) ────────────────────────────────────────────────────────
    "editorWidget.background": "#11141a",
    "editorWidget.border": "#1f2530",
    "editorHoverWidget.background": "#11141a",
    "editorHoverWidget.border": "#1f2530",
    "editorSuggestWidget.background": "#0d1015",
    "editorSuggestWidget.border": "#1f2530",
    "editorSuggestWidget.selectedBackground": "#1a1f29",
    "editorSuggestWidget.highlightForeground": "#4fb0a6",
    "peekViewEditor.background": "#0c0e13",
    "peekViewResult.background": "#07090c",

    // ── Global / shared ─────────────────────────────────────────────────────────────────────────────
    focusBorder: "#4fb0a6",
    foreground: "#c2c8d2",
    descriptionForeground: "#7e8794",
    errorForeground: "#d57a7a",
    "icon.foreground": "#7e8794",
    "selection.background": "#2e4a47cc",
    "widget.border": "#1f2530",
    "sash.hoverBorder": "#4fb0a6",

    // ── Chrome surfaces (sidebar / panel / status / title / tabs) ────────────────────────────────────
    "editorGroup.border": "#1b212a",
    "editorGroupHeader.tabsBackground": "#07090c",
    "panel.background": "#07090c",
    "panel.border": "#1b212a",
    "panelTitle.activeForeground": "#d4d9e1",
    "sideBar.background": "#07090c",
    "sideBar.foreground": "#c2c8d2",
    "sideBar.border": "#1b212a",
    "sideBarSectionHeader.background": "#07090c",
    "activityBar.background": "#07090c",
    "activityBar.foreground": "#d4d9e1",
    "statusBar.background": "#07090c",
    "statusBar.foreground": "#7e8794",
    "statusBar.border": "#1b212a",
    "statusBar.noFolderBackground": "#07090c",
    "statusBarItem.remoteBackground": "#4fb0a6",
    "statusBarItem.remoteForeground": "#06201d",
    "titleBar.activeBackground": "#07090c",
    "titleBar.activeForeground": "#c2c8d2",
    "titleBar.inactiveBackground": "#07090c",
    "titleBar.inactiveForeground": "#5a626f",
    "titleBar.border": "#1b212a",
    "tab.activeBackground": "#0a0c10",
    "tab.activeForeground": "#d4d9e1",
    "tab.inactiveBackground": "#07090c",
    "tab.inactiveForeground": "#5a626f",
    "tab.border": "#1b212a",
    "tab.activeBorderTop": "#4fb0a6",
    "tab.hoverBackground": "#11141a",

    // ── Controls (buttons, inputs, lists, scrollbar) ────────────────────────────────────────────────
    "button.background": "#4fb0a6",
    "button.foreground": "#06201d",
    "button.hoverBackground": "#5cc0b5",
    "button.secondaryBackground": "#1a1f29",
    "button.secondaryForeground": "#d4d9e1",
    "input.background": "#0a0c10",
    "input.foreground": "#d4d9e1",
    "input.border": "#1f2530",
    "input.placeholderForeground": "#5a626f",
    "inputOption.activeBorder": "#4fb0a6",
    "inputOption.activeBackground": "#4fb0a633",
    "dropdown.background": "#11141a",
    "dropdown.border": "#1f2530",
    "list.activeSelectionBackground": "#1a1f29",
    "list.activeSelectionForeground": "#d4d9e1",
    "list.inactiveSelectionBackground": "#141821",
    "list.hoverBackground": "#141821",
    "list.highlightForeground": "#4fb0a6",
    "list.focusBackground": "#1a1f29",
    "scrollbar.shadow": "#00000066",
    "scrollbarSlider.background": "#2a313c80",
    "scrollbarSlider.hoverBackground": "#3a4250aa",
    "scrollbarSlider.activeBackground": "#4a5666cc",
    "badge.background": "#4fb0a6",
    "badge.foreground": "#06201d",
    "progressBar.background": "#4fb0a6",

    // ── Terminal (xterm consumes these) ─────────────────────────────────────────────────────────────
    "terminal.background": "#07090c",
    "terminal.foreground": "#c2c8d2",
    "terminalCursor.foreground": "#5cc0b5",
    "terminal.selectionBackground": "#2e4a4766",
    "terminal.ansiBlack": "#07090c",
    "terminal.ansiRed": "#d57a7a",
    "terminal.ansiGreen": "#b9cda8",
    "terminal.ansiYellow": "#c9a36a",
    "terminal.ansiBlue": "#6f9fd4",
    "terminal.ansiMagenta": "#a98fc9",
    "terminal.ansiCyan": "#4fb0a6",
    "terminal.ansiWhite": "#c2c8d2",
    "terminal.ansiBrightBlack": "#5a626f",
    "terminal.ansiBrightRed": "#df9090",
    "terminal.ansiBrightGreen": "#c9dabb",
    "terminal.ansiBrightYellow": "#d6b37e",
    "terminal.ansiBrightBlue": "#8fb6e0",
    "terminal.ansiBrightMagenta": "#bda0d8",
    "terminal.ansiBrightCyan": "#6fc6bd",
    "terminal.ansiBrightWhite": "#d4d9e1",
  },
  tokenColors: [
    {
      name: "Comment",
      scope: ["comment", "punctuation.definition.comment", "string.comment"],
      settings: { foreground: "#5f6b7a", fontStyle: "italic" },
    },
    {
      name: "String",
      scope: ["string", "string.quoted", "punctuation.definition.string"],
      settings: { foreground: "#b9cda8" },
    },
    {
      name: "String escape / template expression",
      scope: [
        "constant.character.escape",
        "constant.other.placeholder",
        "punctuation.definition.template-expression",
      ],
      settings: { foreground: "#a8c6b6" },
    },
    { name: "Regexp", scope: ["string.regexp"], settings: { foreground: "#abc6b2" } },
    {
      name: "Number",
      scope: ["constant.numeric", "constant.character", "keyword.other.unit"],
      settings: { foreground: "#9bbdb6" },
    },
    {
      name: "Language constant (true/false/null)",
      scope: [
        "constant.language",
        "constant.language.boolean",
        "constant.language.null",
        "constant.language.undefined",
      ],
      settings: { foreground: "#9bbdb6" },
    },
    {
      name: "Keyword / control",
      scope: [
        "keyword",
        "keyword.control",
        "keyword.operator.new",
        "keyword.operator.expression",
        "keyword.operator.logical",
      ],
      settings: { foreground: "#4fb0a6" },
    },
    {
      name: "Storage / type keyword / modifier",
      scope: ["storage", "storage.type", "storage.modifier", "keyword.declaration"],
      settings: { foreground: "#4fb0a6" },
    },
    {
      name: "Operator / accessor",
      scope: ["keyword.operator", "punctuation.accessor", "punctuation.separator"],
      settings: { foreground: "#7e8794" },
    },
    {
      name: "Type / class / namespace",
      scope: [
        "entity.name.type",
        "entity.name.class",
        "entity.name.namespace",
        "support.type",
        "support.class",
        "entity.other.inherited-class",
      ],
      settings: { foreground: "#abb6c4" },
    },
    {
      name: "Function / method",
      scope: [
        "entity.name.function",
        "support.function",
        "meta.function-call entity.name.function",
        "entity.name.function.member",
      ],
      settings: { foreground: "#d0d6df" },
    },
    {
      name: "Variable",
      scope: ["variable", "meta.variable", "variable.other.readwrite"],
      settings: { foreground: "#c2c8d2" },
    },
    {
      name: "Parameter",
      scope: ["variable.parameter", "meta.parameter"],
      settings: { foreground: "#b0b8c4" },
    },
    {
      name: "Property",
      scope: [
        "variable.other.property",
        "variable.other.object.property",
        "support.variable.property",
        "meta.object-literal.key",
      ],
      settings: { foreground: "#c2c8d2" },
    },
    {
      name: "Constant / enum member",
      scope: ["variable.other.constant", "variable.other.enummember"],
      settings: { foreground: "#9bbdb6" },
    },
    {
      name: "Language variable (this / self / super)",
      scope: ["variable.language", "variable.language.this"],
      settings: { foreground: "#4fb0a6", fontStyle: "italic" },
    },
    {
      name: "Tag",
      scope: ["entity.name.tag", "punctuation.definition.tag"],
      settings: { foreground: "#4fb0a6" },
    },
    {
      name: "Tag attribute",
      scope: ["entity.other.attribute-name"],
      settings: { foreground: "#abb6c4" },
    },
    {
      name: "Decorator / annotation",
      scope: [
        "meta.decorator",
        "punctuation.decorator",
        "storage.type.annotation",
        "entity.name.function.decorator",
      ],
      settings: { foreground: "#4fb0a6" },
    },
    {
      name: "JSON key",
      scope: ["support.type.property-name.json", "meta.structure.dictionary.key.json"],
      settings: { foreground: "#c2c8d2" },
    },
    {
      name: "Punctuation / braces",
      scope: ["punctuation", "meta.brace"],
      settings: { foreground: "#7e8794" },
    },
    {
      name: "Markup heading",
      scope: ["markup.heading", "entity.name.section"],
      settings: { foreground: "#4fb0a6", fontStyle: "bold" },
    },
    {
      name: "Markup bold",
      scope: ["markup.bold"],
      settings: { foreground: "#d4d9e1", fontStyle: "bold" },
    },
    {
      name: "Markup italic",
      scope: ["markup.italic"],
      settings: { foreground: "#c2c8d2", fontStyle: "italic" },
    },
    {
      name: "Markup link",
      scope: ["markup.underline.link", "string.other.link"],
      settings: { foreground: "#4fb0a6" },
    },
    {
      name: "Markup inline / fenced code",
      scope: ["markup.inline.raw", "markup.fenced_code"],
      settings: { foreground: "#b9cda8" },
    },
    { name: "Markup inserted", scope: ["markup.inserted"], settings: { foreground: "#b9cda8" } },
    { name: "Markup deleted", scope: ["markup.deleted"], settings: { foreground: "#d57a7a" } },
    { name: "Invalid", scope: ["invalid", "invalid.illegal"], settings: { foreground: "#d57a7a" } },
  ],
  semanticTokenColors: {
    class: "#abb6c4",
    interface: "#abb6c4",
    enum: "#abb6c4",
    struct: "#abb6c4",
    type: "#abb6c4",
    namespace: "#abb6c4",
    typeParameter: "#b0b8c4",
    enumMember: "#9bbdb6",
    function: "#d0d6df",
    method: "#d0d6df",
    macro: "#4fb0a6",
    variable: "#c2c8d2",
    "variable.readonly": "#9bbdb6",
    parameter: "#b0b8c4",
    property: "#c2c8d2",
    "property.readonly": "#c2c8d2",
  },
};
