// "Weavie Dark" — the built-in default theme. Pure-black canvas (#000000) under a small green-forward
// palette, with a single warm amber anchoring types so the eye has somewhere to land. Identifiers are split
// by role not hue — variables italic, properties a lighter upright shade, functions a quiet neutral. The
// same `colors` map drives editor, terminal, and chrome (spec §5).

import type { VsCodeColorTheme } from "../vscode-theme";

/** Stable id Monaco/`setTheme` and the `theme.light`/`theme.dark` settings reference this built-in by. */
export const WEAVIE_DARK_ID = "weavie-dark";

export const WEAVIE_DARK: VsCodeColorTheme = {
  name: "Weavie Dark",
  type: "dark",
  semanticHighlighting: true,
  colors: {
    // ── Editor ────────────────────────────────────────────────────────────────────────────────────
    "editor.background": "#000000",
    "editor.foreground": "#cdd5dc",
    "editorLineNumber.foreground": "#3a3d44",
    "editorLineNumber.activeForeground": "#8e96a2",
    "editorCursor.foreground": "#5fd0a8",
    "editor.selectionBackground": "#28473eaa",
    "editor.selectionHighlightBackground": "#28473e55",
    "editor.inactiveSelectionBackground": "#28473e33",
    "editor.wordHighlightBackground": "#54c6a422",
    "editor.wordHighlightStrongBackground": "#54c6a433",
    "editor.findMatchBackground": "#54c6a455",
    "editor.findMatchHighlightBackground": "#54c6a42e",
    "editor.lineHighlightBackground": "#0c0d1066",
    "editor.lineHighlightBorder": "#00000000",
    "editorWhitespace.foreground": "#20242b",
    "editorIndentGuide.background1": "#16191f",
    "editorIndentGuide.activeBackground1": "#54c6a444",
    "editorBracketMatch.background": "#54c6a41f",
    "editorBracketMatch.border": "#54c6a477",
    "editorBracketHighlight.foreground1": "#54c6a4",
    "editorBracketHighlight.foreground2": "#ffb74d",
    "editorBracketHighlight.foreground3": "#b0bcc8",
    "editorRuler.foreground": "#16191f",
    "editorGutter.addedBackground": "#5a9a6a",
    "editorGutter.modifiedBackground": "#54c6a4",
    "editorGutter.deletedBackground": "#c47a7a",
    "editorOverviewRuler.addedForeground": "#5a9a6ab3",
    "editorOverviewRuler.deletedForeground": "#c47a7ab3",
    "editorError.foreground": "#e07a7a",

    // ── Diff (inline change review + standalone diff editor) ────────────────────────────────────────
    // Dark, saturated green washes keep muted syntax (especially comments) legible when the layers stack.
    "diffEditor.insertedLineBackground": "#2ea04314",
    "diffEditor.insertedTextBackground": "#2ea04324",
    "diffEditor.removedLineBackground": "#c47a7a21",
    "diffEditor.removedTextBackground": "#c47a7a3d",
    "editorWarning.foreground": "#e0b060",
    "editorInfo.foreground": "#54c6a4",

    // ── Inlay hints (parameter-name / type chips) ───────────────────────────────────────────────────
    // Quiet and chip-less so they annotate without competing with the code they sit between.
    "editorInlayHint.foreground": "#565b62",
    "editorInlayHint.background": "#00000000",
    "editorInlayHint.typeForeground": "#565b62",
    "editorInlayHint.parameterForeground": "#565b62",

    // ── Widgets (hover, suggest, find, peek) ────────────────────────────────────────────────────────
    "editorWidget.background": "#101319",
    "editorWidget.border": "#212834",
    "editorHoverWidget.background": "#101319",
    "editorHoverWidget.border": "#212834",
    "editorSuggestWidget.background": "#0b0d11",
    "editorSuggestWidget.border": "#212834",
    "editorSuggestWidget.selectedBackground": "#161a21",
    "editorSuggestWidget.highlightForeground": "#54c6a4",
    "peekViewEditor.background": "#050608",
    "peekViewResult.background": "#0a0b0e",

    // ── Global / shared ─────────────────────────────────────────────────────────────────────────────
    focusBorder: "#54c6a4",
    foreground: "#c8d0dc",
    descriptionForeground: "#6f7884",
    errorForeground: "#e07a7a",
    "icon.foreground": "#7e8794",
    "selection.background": "#28473ecc",
    "widget.border": "#212834",
    "sash.hoverBorder": "#54c6a4",

    // ── Chrome surfaces (sidebar / panel / status / title / tabs) ────────────────────────────────────
    // One step lighter than the editor, so the canvas reads as the focal well it frames.
    "editorGroup.border": "#191c21",
    "editorGroupHeader.tabsBackground": "#0a0b0e",
    "panel.background": "#0a0b0e",
    "panel.border": "#191c21",
    "panelTitle.activeForeground": "#cdd5dc",
    "sideBar.background": "#0a0b0e",
    "sideBar.foreground": "#c2cad4",
    "sideBar.border": "#191c21",
    "sideBarSectionHeader.background": "#0a0b0e",
    "activityBar.background": "#0a0b0e",
    "activityBar.foreground": "#cdd5dc",
    "statusBar.background": "#0a0b0e",
    "statusBar.foreground": "#7e8794",
    "statusBar.border": "#191c21",
    "statusBar.noFolderBackground": "#0a0b0e",
    "statusBarItem.remoteBackground": "#54c6a4",
    "statusBarItem.remoteForeground": "#042019",
    "titleBar.activeBackground": "#0a0b0e",
    "titleBar.activeForeground": "#c8d0dc",
    "titleBar.inactiveBackground": "#0a0b0e",
    "titleBar.inactiveForeground": "#5a626c",
    "titleBar.border": "#191c21",
    "tab.activeBackground": "#000000",
    "tab.activeForeground": "#eef2f8",
    "tab.inactiveBackground": "#0a0b0e",
    "tab.inactiveForeground": "#5a626c",
    "tab.border": "#191c21",
    "tab.activeBorderTop": "#54c6a4",
    "tab.hoverBackground": "#101319",

    // ── Controls (buttons, inputs, lists, scrollbar) ────────────────────────────────────────────────
    "button.background": "#54c6a4",
    "button.foreground": "#042019",
    "button.hoverBackground": "#63d2b1",
    "button.secondaryBackground": "#161a21",
    "button.secondaryForeground": "#cdd5dc",
    "input.background": "#08090b",
    "input.foreground": "#cdd5dc",
    "input.border": "#212834",
    "input.placeholderForeground": "#5a626c",
    "inputOption.activeBorder": "#54c6a4",
    "inputOption.activeBackground": "#54c6a433",
    "dropdown.background": "#101319",
    "dropdown.border": "#212834",
    "list.activeSelectionBackground": "#161a21",
    "list.activeSelectionForeground": "#eef2f8",
    "list.inactiveSelectionBackground": "#111419",
    "list.hoverBackground": "#111419",
    "list.highlightForeground": "#54c6a4",
    "list.focusBackground": "#161a21",
    "scrollbar.shadow": "#00000066",
    "scrollbarSlider.background": "#2a313c80",
    "scrollbarSlider.hoverBackground": "#3a4250aa",
    "scrollbarSlider.activeBackground": "#4a5666cc",
    "badge.background": "#54c6a4",
    "badge.foreground": "#042019",
    "progressBar.background": "#54c6a4",

    // ── Terminal (xterm consumes these) ─────────────────────────────────────────────────────────────
    "terminal.background": "#08090c",
    "terminal.foreground": "#c8d0dc",
    "terminalCursor.foreground": "#5fd0a8",
    "terminal.selectionBackground": "#28473e66",
    "terminal.ansiBlack": "#45484f",
    "terminal.ansiRed": "#e07a7a",
    "terminal.ansiGreen": "#6fdc66",
    "terminal.ansiYellow": "#ffb74d",
    "terminal.ansiBlue": "#6fa8e0",
    "terminal.ansiMagenta": "#c08cff",
    "terminal.ansiCyan": "#5fd0c0",
    "terminal.ansiWhite": "#c8d0dc",
    "terminal.ansiBrightBlack": "#6f7884",
    "terminal.ansiBrightRed": "#f08e8e",
    "terminal.ansiBrightGreen": "#8ce884",
    "terminal.ansiBrightYellow": "#ffca78",
    "terminal.ansiBrightBlue": "#8fc0f0",
    "terminal.ansiBrightMagenta": "#d0a8ff",
    "terminal.ansiBrightCyan": "#7fe0d0",
    "terminal.ansiBrightWhite": "#eef2f8",
  },
  tokenColors: [
    {
      name: "Comment",
      scope: ["comment", "punctuation.definition.comment", "string.comment"],
      settings: { foreground: "#45484f", fontStyle: "italic" },
    },
    {
      name: "String",
      scope: ["string", "string.quoted", "punctuation.definition.string"],
      settings: { foreground: "#6fdc66" },
    },
    {
      name: "String escape / template expression",
      scope: [
        "constant.character.escape",
        "constant.other.placeholder",
        "punctuation.definition.template-expression",
      ],
      settings: { foreground: "#84e07a" },
    },
    { name: "Regexp", scope: ["string.regexp"], settings: { foreground: "#84e07a" } },
    {
      name: "Number",
      scope: ["constant.numeric", "constant.character", "keyword.other.unit"],
      settings: { foreground: "#5fd0a8" },
    },
    {
      name: "Language constant (true/false/null)",
      scope: [
        "constant.language",
        "constant.language.boolean",
        "constant.language.null",
        "constant.language.undefined",
      ],
      settings: { foreground: "#5fd0a8" },
    },
    {
      name: "Keyword / control",
      scope: [
        "keyword",
        "keyword.control",
        "keyword.operator.new",
        "keyword.operator.expression",
        "keyword.operator.logical",
      ],
      settings: { foreground: "#5fa295" },
    },
    {
      name: "Storage / type keyword / modifier",
      scope: ["storage", "storage.type", "storage.modifier", "keyword.declaration"],
      settings: { foreground: "#5fa295" },
    },
    {
      name: "Operator / accessor",
      scope: ["keyword.operator", "punctuation.accessor", "punctuation.separator"],
      settings: { foreground: "#6f7b8a" },
    },
    {
      name: "Type / class / namespace",
      scope: [
        "entity.name.type",
        "entity.name.class",
        "entity.name.namespace",
        "support.type",
        "support.class",
        "entity.other.inherited-class",
      ],
      settings: { foreground: "#ffb74d" },
    },
    {
      name: "Function / method",
      scope: [
        "entity.name.function",
        "support.function",
        "meta.function-call entity.name.function",
        "entity.name.function.member",
      ],
      settings: { foreground: "#aeb8c2" },
    },
    {
      name: "Variable",
      scope: [
        "variable",
        "meta.variable",
        "variable.other.readwrite",
        "variable.parameter",
        "meta.parameter",
      ],
      settings: { foreground: "#d4dce6", fontStyle: "italic" },
    },
    {
      name: "Property",
      scope: [
        "variable.other.property",
        "variable.other.object.property",
        "support.variable.property",
        "meta.object-literal.key",
      ],
      settings: { foreground: "#f2f6fc" },
    },
    {
      name: "Constant / enum member",
      scope: ["variable.other.constant", "variable.other.enummember"],
      settings: { foreground: "#5fd0a8" },
    },
    {
      name: "Language variable (this / self / super)",
      scope: ["variable.language", "variable.language.this"],
      settings: { foreground: "#5fa295", fontStyle: "italic" },
    },
    {
      name: "Tag",
      scope: ["entity.name.tag", "punctuation.definition.tag"],
      settings: { foreground: "#5fa295" },
    },
    {
      name: "Tag attribute",
      scope: ["entity.other.attribute-name"],
      settings: { foreground: "#b0bcc8" },
    },
    {
      name: "Decorator / annotation",
      scope: [
        "meta.decorator",
        "punctuation.decorator",
        "storage.type.annotation",
        "entity.name.function.decorator",
      ],
      settings: { foreground: "#ffb74d" },
    },
    {
      name: "JSON key",
      scope: ["support.type.property-name.json", "meta.structure.dictionary.key.json"],
      settings: { foreground: "#f2f6fc" },
    },
    {
      name: "Punctuation / braces",
      scope: ["punctuation", "meta.brace"],
      settings: { foreground: "#6f7b8a" },
    },
    {
      name: "Markup heading",
      scope: ["markup.heading", "entity.name.section"],
      settings: { foreground: "#ffb74d", fontStyle: "bold" },
    },
    {
      name: "Markup bold",
      scope: ["markup.bold"],
      settings: { foreground: "#eef2f8", fontStyle: "bold" },
    },
    {
      name: "Markup italic",
      scope: ["markup.italic"],
      settings: { foreground: "#cdd5dc", fontStyle: "italic" },
    },
    {
      name: "Markup link",
      scope: ["markup.underline.link", "string.other.link"],
      settings: { foreground: "#54c6a4" },
    },
    {
      name: "Markup inline / fenced code",
      scope: ["markup.inline.raw", "markup.fenced_code"],
      settings: { foreground: "#6fdc66" },
    },
    { name: "Markup inserted", scope: ["markup.inserted"], settings: { foreground: "#6fdc66" } },
    { name: "Markup deleted", scope: ["markup.deleted"], settings: { foreground: "#e07a7a" } },
    { name: "Invalid", scope: ["invalid", "invalid.illegal"], settings: { foreground: "#e07a7a" } },
  ],
  semanticTokenColors: {
    // Types take the lone warm amber accent — the one colour that grabs the eye; namespaces dimmed (qualifiers).
    class: "#ffb74d",
    interface: "#ffb74d",
    enum: "#ffb74d",
    struct: "#ffb74d",
    type: "#ffb74d",
    typeParameter: "#e0b878",
    namespace: "#c89a58",
    // Literal values (numbers, constants, enum members) share the sea-green of numbers.
    enumMember: "#5fd0a8",
    number: "#5fd0a8",
    "variable.readonly": "#5fd0a8",
    // Functions are a quiet neutral — call sites read by shape, not colour; keywords/strings stay green.
    function: "#aeb8c2",
    method: "#aeb8c2",
    macro: "#5fa295",
    keyword: "#5fa295",
    string: "#6fdc66",
    operator: "#6f7b8a",
    comment: { foreground: "#45484f", fontStyle: "italic" },
    // Variables (incl. parameters) are italic — the data flowing through; properties a lighter upright shade.
    variable: { foreground: "#d4dce6", fontStyle: "italic" },
    parameter: { foreground: "#d4dce6", fontStyle: "italic" },
    property: "#f2f6fc",
    "property.readonly": "#f2f6fc",
  },
};
